# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90566c69c2b06c656682181a6e909e3e01853195881e7f8149aad19b19ba5408f88fa839f37567313fad7ee54db05cf8fb1bf606a85292d1513c6331e2e68091

test:
  secret_key_base: 6c178b87f42e2eacc5e7160825e5acd5eed994e40507a3e774770672d5ff08a0e5f801d577cb0b824932e5c5e0c3c613b6588ec79de0240faf530b0418438c19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
